### ISSUE TITLE
Merging with main repo

### ISSUE THREAD

**Issue by greduan** [luckyshot/chrome-ext-tabulator#3]
Heya @luckyshot,

@jaredly contacted me by email recently to add to the main repo's README links to the active forks, and what came out of it was a proposal from me to simply give you and him push access to the main repo so the main repo can continue to receive updates and make best use of the SEO that it has gathered by virtue of being one of the first to take these keywords.

What do you think of that idea? Let me know so we can organize it if you're interested :slightly_smiling_face:

**Comment by luckyshot** [comment]
Hi @greduan 

That sounds great! This way we won't bother you with PRs all the time and this great extension can continue to grow 😊

@greduan @jaredly How do you think we should do this? 
Should we merge /luckyshot/ fork with the /greduan/ one?

**Comment by jaredly** [comment]
Yup that makes sense to me

**Comment by greduan** [comment]
Sorry for delay, in middle of vacation :slightly_smiling_face: 

Makes sense to me to merge `luckyshot` to `greduan`. Let me know what you need me to do with the repo. For now I'll unarchive it and add you two to the as maintainers.

Easier to reach me by email, fyi :slightly_smiling_face:
